table fact_include_controller_daily
	lineageTag: 27705b89-57ac-44d8-b090-93f35ee7d1e3

	column site_id
		dataType: double
		lineageTag: d73ffb83-97a8-4945-bb71-f3990c97cc09
		summarizeBy: none
		sourceColumn: site_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column request_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: db5f4f87-36a5-438a-8d17-fdf5f92ec250
		summarizeBy: none
		sourceColumn: request_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column main_controller_name
		dataType: string
		lineageTag: 9d733312-b6af-4ec7-b92c-4093c8163b00
		summarizeBy: none
		sourceColumn: main_controller_name

		annotation SummarizationSetBy = Automatic

	column controller_name
		dataType: string
		lineageTag: d27e7e0a-bdaf-4e35-bce6-89ddfad1fa2a
		summarizeBy: none
		sourceColumn: controller_name

		annotation SummarizationSetBy = Automatic

	column total_requests
		dataType: double
		lineageTag: 7837c33a-b7f1-4165-a523-07b5c27665ff
		summarizeBy: sum
		sourceColumn: total_requests

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_response_time_ms
		dataType: double
		lineageTag: 36798a0a-1f76-4642-93f0-6329762ca7da
		summarizeBy: sum
		sourceColumn: total_response_time_ms

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cache_hit_requests
		dataType: double
		lineageTag: 7844178d-8cce-45a4-afe4-1263350d88cf
		summarizeBy: sum
		sourceColumn: cache_hit_requests

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_response_time_ms
		dataType: double
		lineageTag: fff4b635-d9e9-406f-91ef-5f93dae705b9
		summarizeBy: sum
		sourceColumn: avg_response_time_ms

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_requests_main
		dataType: double
		lineageTag: bc392c86-ca83-472c-aeb2-e8f64b83363b
		summarizeBy: sum
		sourceColumn: total_requests_main

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column percent_of_main_requests
		dataType: double
		lineageTag: 957e4e66-06c9-4582-99c6-26a9b6f7724c
		summarizeBy: sum
		sourceColumn: percent_of_main_requests

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_include_controller_daily = m
		mode: import
		queryGroup: 'Lot 2'
		source =
				let
				  read_csv               = FX_ReadCsv("ccdw_aggr_include_controller_request_aaqp_prd.csv"),
				  typecast_fields        = Table.TransformColumns(read_csv,{
				                            {"site_id", each try Number.From(_) otherwise null, type number},
				                            {"request_date", each DateTime.Date(DateTime.From(_)), type date},
				                            {"main_controller_name", each Text.From(_), type text},
				                            {"controller_name", each Text.From(_), type text},
				                            {"cache_behavior", each Text.Upper(Text.From(_)), type text},
				                            {"status_code", each Text.From(_), type text},
				                            {"num_requests", each try Number.From(_) otherwise 0, type number},
				                            {"response_time", each try Number.From(_) otherwise 0, type number}}),
				  add_cache_hit_flag     = Table.AddColumn(typecast_fields,"cache_hit_requests", each if [cache_behavior]="HIT" then [num_requests] else 0, type number),
				  group_include          = Table.Group(add_cache_hit_flag, {"site_id","request_date","main_controller_name","controller_name"},
				                            {{"total_requests", each List.Sum([num_requests]), type number},
				                             {"total_response_time_ms", each List.Sum([response_time]), type number},
				                             {"cache_hit_requests", each List.Sum([cache_hit_requests]), type number}}),
				  add_avg_ms             = Table.AddColumn(group_include,"avg_response_time_ms", each if [total_requests]=0 then 0 else [total_response_time_ms]/[total_requests], type number),
				  total_by_main          = Table.Group(add_avg_ms, {"site_id","request_date","main_controller_name"}, {{"total_requests_main", each List.Sum([total_requests]), type number}}),
				  join_total_main        = Table.NestedJoin(add_avg_ms, {"site_id","request_date","main_controller_name"}, total_by_main, {"site_id","request_date","main_controller_name"}, "m", JoinKind.LeftOuter),
				  expand_total_main      = Table.ExpandTableColumn(join_total_main, "m", {"total_requests_main"}, {"total_requests_main"}),
				  add_percent_of_main    = Table.AddColumn(expand_total_main,"percent_of_main_requests", each if [total_requests_main]=null or [total_requests_main]=0 then 0 else [total_requests]/[total_requests_main], type number)
				in
				  add_percent_of_main

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

