table fact_include_cache_daily
	lineageTag: f09cbb6d-cb50-44c6-be4c-0584fc51276f

	column site_id
		dataType: double
		lineageTag: 84144719-2e4e-4e38-ad2f-878fa008b6e8
		summarizeBy: none
		sourceColumn: site_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column request_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b3967259-819f-439e-9f96-849cbe97840e
		summarizeBy: none
		sourceColumn: request_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column main_controller_name
		dataType: string
		lineageTag: 3a2bee77-7595-4e85-9213-aa39d7736995
		summarizeBy: none
		sourceColumn: main_controller_name

		annotation SummarizationSetBy = Automatic

	column controller_name
		dataType: string
		lineageTag: afc9a4c7-f0a4-4ceb-b1f9-5925ff5bb213
		summarizeBy: none
		sourceColumn: controller_name

		annotation SummarizationSetBy = Automatic

	column total_requests
		dataType: double
		lineageTag: 05d667d1-d9ca-49f8-97ef-edf0dce54e00
		summarizeBy: sum
		sourceColumn: total_requests

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cache_hit_requests
		dataType: double
		lineageTag: 3131c958-01f5-4fb2-ab81-7ed27dd2ba29
		summarizeBy: sum
		sourceColumn: cache_hit_requests

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cache_miss_requests
		dataType: double
		lineageTag: ecc78912-67b0-4d1c-93c2-c5e76f1bebcb
		summarizeBy: sum
		sourceColumn: cache_miss_requests

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cache_miss_and_store_requests
		dataType: double
		lineageTag: 278c11b3-ccba-4218-b457-ab1684de57cf
		summarizeBy: sum
		sourceColumn: cache_miss_and_store_requests

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cache_hit_rate
		dataType: double
		lineageTag: df804445-f7cb-470b-9d46-0ca270c118e0
		summarizeBy: sum
		sourceColumn: cache_hit_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cache_miss_rate
		dataType: double
		lineageTag: cbb9f80c-a3bf-43b5-9ffc-791c09186a83
		summarizeBy: sum
		sourceColumn: cache_miss_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cache_miss_and_store_rate
		dataType: double
		lineageTag: 90de415e-99ef-4756-baa5-a1bc3c29649a
		summarizeBy: sum
		sourceColumn: cache_miss_and_store_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_include_cache_daily = m
		mode: import
		queryGroup: 'Lot 2'
		source =
				let
				  read_csv                     = FX_ReadCsv("ccdw_aggr_include_controller_request_aaqp_prd.csv"),
				  typecast_fields              = Table.TransformColumns(read_csv,{
				                                {"site_id", each try Number.From(_) otherwise null, type number},
				                                {"request_date", each DateTime.Date(DateTime.From(_)), type date},
				                                {"main_controller_name", each Text.From(_), type text},
				                                {"controller_name", each Text.From(_), type text},
				                                {"cache_behavior", each Text.Upper(Text.From(_)), type text},
				                                {"num_requests", each try Number.From(_) otherwise 0, type number}
				                              }),
				
				  add_cache_miss_requests      = Table.AddColumn(typecast_fields, "cache_miss_requests",
				                                each if [cache_behavior]="MISS" then [num_requests] else 0, type number),
				
				  add_cache_miss_store_requests= Table.AddColumn(add_cache_miss_requests, "cache_miss_and_store_requests",
				                                each if [cache_behavior]="MISSANDSTORE" then [num_requests] else 0, type number),
				
				  add_cache_hit_requests       = Table.AddColumn(add_cache_miss_store_requests, "cache_hit_requests",
				                                each if [cache_behavior]="HIT" then [num_requests] else 0, type number),
				
				  group_cache                  = Table.Group(add_cache_hit_requests,
				                                {"site_id","request_date","main_controller_name","controller_name"},
				                                {
				                                  {"total_requests", each List.Sum([num_requests]), type number},
				                                  {"cache_hit_requests", each List.Sum([cache_hit_requests]), type number},
				                                  {"cache_miss_requests", each List.Sum([cache_miss_requests]), type number},
				                                  {"cache_miss_and_store_requests", each List.Sum([cache_miss_and_store_requests]), type number}
				                                }),
				
				  add_cache_hit_rate           = Table.AddColumn(group_cache, "cache_hit_rate",
				                                each if [total_requests]=0 then 0 else [cache_hit_requests]/[total_requests], type number),
				
				  add_cache_miss_rate          = Table.AddColumn(add_cache_hit_rate, "cache_miss_rate",
				                                each if [total_requests]=0 then 0 else [cache_miss_requests]/[total_requests], type number),
				
				  add_cache_miss_store_rate    = Table.AddColumn(add_cache_miss_rate, "cache_miss_and_store_rate",
				                                each if [total_requests]=0 then 0 else [cache_miss_and_store_requests]/[total_requests], type number)
				in
				  add_cache_miss_store_rate

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

